name: github-actions-sandbox

on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test cmd
        run: cd cmd && go test -v ./... && cd ..
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build test
        run: sh scripts/build.sh
